import type { ModuleDefinition, ModuleId } from './types'

export const MODULE_REGISTRY: Record<ModuleId, ModuleDefinition> = {
  skills: {
    id: 'skills',
    name: 'Skills',
    description: 'All 18 skills grouped by ability',
    defaultColumn: 0,
    defaultOrder: 0,
    canCollapse: true,
    canHide: true,
  },
  'saving-throws': {
    id: 'saving-throws',
    name: 'Saving Throws',
    description: 'Six saving throws with proficiency',
    defaultColumn: 0,
    defaultOrder: 1,
    canCollapse: true,
    canHide: false,
  },
  resources: {
    id: 'resources',
    name: 'Resources',
    description: 'Limited features and hit dice',
    defaultColumn: 0,
    defaultOrder: 2,
    canCollapse: true,
    canHide: true,
  },
  'temp-hp': {
    id: 'temp-hp',
    name: 'Temporary HP',
    description: 'Temporary hit points tracker',
    defaultColumn: 0,
    defaultOrder: 3,
    canCollapse: false,
    canHide: true,
  },
  conditions: {
    id: 'conditions',
    name: 'Conditions',
    description: 'Active conditions tracker',
    defaultColumn: 0,
    defaultOrder: 4,
    canCollapse: true,
    canHide: true,
  },
  exhaustion: {
    id: 'exhaustion',
    name: 'Exhaustion',
    description: 'Exhaustion level (1-6)',
    defaultColumn: 0,
    defaultOrder: 5,
    canCollapse: false,
    canHide: true,
  },
  'death-saves': {
    id: 'death-saves',
    name: 'Death Saves',
    description: 'Death saving throws',
    defaultColumn: 0,
    defaultOrder: 6,
    canCollapse: false,
    canHide: true,
    conditionalRender: 'at-zero-hp',
  },
  concentration: {
    id: 'concentration',
    name: 'Concentration',
    description: 'Current concentration spell',
    defaultColumn: 0,
    defaultOrder: 7,
    canCollapse: false,
    canHide: true,
    conditionalRender: 'when-concentrating',
  },
  'combat-stats': {
    id: 'combat-stats',
    name: 'Combat Stats',
    description: 'AC, Initiative, Speed',
    defaultColumn: 1,
    defaultOrder: 0,
    canCollapse: false,
    canHide: false,
  },
  proficiency: {
    id: 'proficiency',
    name: 'Proficiency Bonus',
    description: 'Proficiency bonus display',
    defaultColumn: 1,
    defaultOrder: 1,
    canCollapse: false,
    canHide: true,
  },
  'hit-points': {
    id: 'hit-points',
    name: 'Hit Points',
    description: 'HP tracker with rest buttons',
    defaultColumn: 1,
    defaultOrder: 2,
    canCollapse: false,
    canHide: false,
  },
  'ability-scores': {
    id: 'ability-scores',
    name: 'Ability Scores',
    description: 'Six ability scores with modifiers',
    defaultColumn: 1,
    defaultOrder: 3,
    canCollapse: false,
    canHide: false,
  },
  'info-tabs': {
    id: 'info-tabs',
    name: 'Character Info',
    description: 'Summary, Race Traits, Class Features tabs',
    defaultColumn: 1,
    defaultOrder: 4,
    canCollapse: true,
    canHide: true,
  },
  'story-tabs': {
    id: 'story-tabs',
    name: 'Main Content',
    description: 'Story, Actions, Features, Spells tabs',
    defaultColumn: 2,
    defaultOrder: 0,
    canCollapse: false,
    canHide: false,
  },
  spellbook: {
    id: 'spellbook',
    name: 'Spellbook',
    description: 'Spellbook drawer',
    defaultColumn: 2,
    defaultOrder: 1,
    canCollapse: false,
    canHide: false,
    conditionalRender: 'caster-only',
  },
  chronicle: {
    id: 'chronicle',
    name: "Archivist's Chronicle",
    description: 'AI-generated backstory and notes',
    defaultColumn: 2,
    defaultOrder: 2,
    canCollapse: true,
    canHide: true,
  },
  quirks: {
    id: 'quirks',
    name: 'Quirks',
    description: 'Character quirks',
    defaultColumn: 2,
    defaultOrder: 3,
    canCollapse: true,
    canHide: true,
  },
  inventory: {
    id: 'inventory',
    name: 'Inventory',
    description: 'Character inventory and equipment',
    defaultColumn: 2,
    defaultOrder: 4,
    canCollapse: true,
    canHide: true,
  },
}

export const ALL_MODULE_IDS = Object.keys(MODULE_REGISTRY) as ModuleId[]
